version: '3.8'

networks:
  postgreNet:
    name: postgreNet
    driver: bridge

volumes:
  postgree-db:


services:
  postgree-db:
    image: postgres:latest
    container_name: postgres-db
    networks:
      - postgreNet
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: admin
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/data/postgres